apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    # Istio will user app and version
    app: user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: "1.0"
  template:
    metadata:
      labels:
        app: user-service
        version: "1.0"
    spec:
      containers:
      - name: user-service
        image: registry.cn-hangzhou.aliyuncs.com/my-istio-release/user-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /health
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui-deployment
  labels:
    app: user-ui-deployment
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        version: "1.0"
    spec:
      containers:
      - name: user-ui
        image: registry.cn-hangzhou.aliyuncs.com/my-istio-release/user-ui:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /health
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-ui
spec:
  selector:
    app: user-ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
